#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Oct 27, 2021 04:21:49 PM +03  platform: Windows NT

import sys
from tkinter import  Canvas
from tkinter.constants import BOTTOM, LEFT, NW, TOP, X, Y
from PIL import Image, ImageTk

# İnternet olmadığında örnek üzerinde çalışmak için (13-90-105-127-117). satırlar yorum haline getirilir.
#from nob_ecz_bilgi_getir import wet

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True
import excanedeneme_support


def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    excanedeneme_support.set_Tk_var()
    top = Toplevel1 (root)
    excanedeneme_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    root = rt
    w = tk.Toplevel (root)
    excanedeneme_support.set_Tk_var()
    top = Toplevel1 (w)
    excanedeneme_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("1400x700")
        top.minsize(120, 1)
        top.maxsize(3290, 1061)
        top.resizable(1,  1)
        top.title("Nöbetçi Eczaneler")
        top.configure(background="#d9d9d9")

        # Başlık Label
        self.nob_ecz = tk.Label(top)
        self.nob_ecz.pack()
        self.nob_ecz.configure(background="#d9d9d9")
        self.nob_ecz.configure(disabledforeground="#a3a3a3")
        self.nob_ecz.configure(font="-family {Times New Roman} -size 20")
        self.nob_ecz.configure(foreground="#0000ff")
        self.nob_ecz.configure(text='''\nNÖBETÇİ ECZANELER''')

        # Nöbetçi eczane adı
        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.047, rely=0.157)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(justify='left')
        self.Label1.configure(foreground="#000000")
        #self.Label1.configure(text='''NOBETÇİ ECZANE ADI: \n'''+wet.nob_olan_ecz)
        self.Label1.configure(text='''NOBETÇİ ECZANE ADI: \n'''+"ŞULE ECZANESİ")


        # Adres
        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.031, rely=0.217, height=67, width=200)
        #self.Label2.configure(anchor='nw')
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(compound='center')
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#f0f0f0f0f0f0")
        self.Label2.configure(justify='left')
        self.Label2.configure(takefocus="2")
        #self.Label2.configure(text='''Adres: '''+wet.nob_olan_ecz_adres+" "+wet.ek_adres_bilgisi)
        self.Label2.configure(text='''Adres: '''+"UĞUR MUMCU BULVARI KARİNA EVLERİ NO2 D25 NİLÜFER BURSA")
        self.Label2.configure(wraplength="150")

        # Telefon numarası
        self.Label3 = tk.Label(top)
        self.Label3.place(relx=0.031, rely=0.333, height=26, width=200)
        #self.Label3.configure(anchor='w')
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(justify='left')
        #self.Label3.configure(text='Tel: '+wet.nob_olan_ecz_telefon)
        self.Label3.configure(text='Tel: '+"02244244224")
        self.Label4 = tk.Label(top)
        self.Label4.place(relx=0.031, rely=0.378, height=53, width=200)
        
        # Nöbet tarihleri
        #self.Label4.configure(anchor='nw')
        self.Label4.configure(background="#d9d9d9")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        #self.Label4.configure(text="Bugün "+wet.nob_olan_ecz_nobettarihleri)
        self.Label4.configure(text="Bugün "+"SAAT 18.00DAN İTİBAREN ŞULE ECZANESİ NÖBET HALİNDE AÇIK OLACAKTIR.")
        self.Label4.configure(wraplength="150")

        
        googleresim=ImageTk.PhotoImage(file="googlegunluk.jpeg")
        self.canvas = tk.Canvas(top, width=500,height=400)
        self.canvas.place(relx=0.25,rely=0.25)

        # Güncellenmeli!!!!!!
        # Harita image
        load = Image.open("googlegunluk.jpeg")
        load= load.resize((500,400))
        self.canvas.image=ImageTk.PhotoImage(load)
        self.canvas.create_image(0,0,image=self.canvas.image,anchor='nw')
 
  

if __name__ == '__main__':
    #wet.nob_ecz_bul() #nobetci eczane jpeg yap
    vp_start_gui()





