#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Oct 27, 2021 04:21:49 PM +03  platform: Windows NT

import sys
from tkinter import  Canvas
from tkinter.constants import NW, TOP, X, Y
from PIL import Image, ImageTk
#from nob_ecz_bilgi_getir import wet

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True
import excanedeneme_support


def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    excanedeneme_support.set_Tk_var()
    top = Toplevel1 (root)
    excanedeneme_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    excanedeneme_support.set_Tk_var()
    top = Toplevel1 (w)
    excanedeneme_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("800x600+450+189")
        top.minsize(120, 1)
        top.maxsize(3290, 1061)
        top.resizable(1,  1)
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")

        self.nob_ecz = tk.Label(top)
        self.nob_ecz.place(relx=0.0, rely=0.0, height=94, width=800)
        self.nob_ecz.configure(background="#d9d9d9")
        self.nob_ecz.configure(disabledforeground="#a3a3a3")
        self.nob_ecz.configure(font="-family {Times New Roman} -size 14")
        self.nob_ecz.configure(foreground="#000000")
        self.nob_ecz.configure(text='''NÖBETÇİ ECZANELER2''')

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.0, rely=0.157, height=41, width=232)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''NOBETÇİ ECZANE ADI''')

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.031, rely=0.217, height=67, width=200)
        self.Label2.configure(anchor='nw')
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(compound='center')
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#f0f0f0f0f0f0")
        self.Label2.configure(justify='left')
        self.Label2.configure(takefocus="2")
        self.Label2.configure(text='''Nöbetçi eczane adresi bilgiler uzun olacak ki alt satıra kaysın''')
        self.Label2.configure(textvariable=excanedeneme_support.bu0)
        self.Label2.configure(wraplength="150")

        self.Label3 = tk.Label(top)
        self.Label3.place(relx=0.031, rely=0.333, height=26, width=200)
        self.Label3.configure(anchor='w')
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(justify='left')
        self.Label3.configure(text='''Tel :''')

        self.Label4 = tk.Label(top)
        self.Label4.place(relx=0.031, rely=0.378, height=53, width=200)
        
        self.Label4.configure(anchor='nw')
        self.Label4.configure(background="#d9d9d9")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(text='''Bugün saat / yarın saat arası nöbetçidir.''')
        self.Label4.configure(wraplength="150")

        
        googleresim=ImageTk.PhotoImage(file="googlegunluk.jpeg")
        self.canvas = tk.Canvas(top, width=500,height=400)
        self.canvas.place(relx=0.25,rely=0.25)

        load = Image.open("googlegunluk.jpeg")
        load= load.resize((500,400))
        self.canvas.image=ImageTk.PhotoImage(load)
        self.canvas.create_image(50,50,image=self.canvas.image,anchor='nw')
 
  

if __name__ == '__main__':
    #wet.nob_ecz_bul() #nobetci eczane jpeg yap
    vp_start_gui()





